package com.example.srs.enums;

public enum ERRORCODE {
    INVALID_INPUT_DATA,
    //400
    COURSE_NOT_AVAILABLE,
    //401
    UNAUTHORIZED,
    EXPIRED_JWT_TOKEN,
    INVALID_JWT_TOKEN,
    //403
    FORBIDDEN,
    // 404
    USER_NOTFOUND,
    ROLE_NOTFOUND,
    COURSE_NOTFOUND,
    LESSON_NOTFOUND,
    ENROLLMENT_NOTFOUND,
    LESSON_PROGRESS_NOTFOUND,
    NOTIFICATION_NOTFOUND,
    //409
    USER_ALREADY_EXISTS,
    ROLE_ALREADY_EXISTS,
    STUDENT_ENROLL_ALREADY_EXISTS,
    //500
    SYSTEM_ERROR,

    JWT_ERROR
}
